### ISSUE TITLE
Cikkekhez több író is lehessen

### ISSUE THREAD

**Issue by dexmona** [legokor/legokor.hu#12]

**Comment by Szibence** [comment]
Egy dolgot kivéve kész: az írók felsorolásában a vesszők előtt van egy space karakter.

**Comment by martonbognar** [comment]
ezt nezted? https://shopify.github.io/liquid/basics/whitespace/

**Comment by Szibence** [comment]
Néztem, próbáltam is mindenhogy, de az nem segít. Lehet az csak az üres sorok kiküszöbölésére van.

**Comment by martonbognar** [comment]
A cikkek oldalra most elvileg megcsinaltam rendesen (16a237a3ab7ffc826bba0e409cf2e2b2e12eb35f), az onallo post oldalt meghagyom neked ;)

**Comment by Szibence** [comment]
Huh, az igen :D az igazi magic az az else utáni vessző lehetett
