### ISSUE TITLE
Minden projekt aktivnak van jelezve a sajat oldalan

### ISSUE THREAD

**Issue by martonbognar** [legokor/legokor.hu#16]
Jelenleg minden projekt oldalan latszik az a szoveg, hogy 
> A projekt jelenleg is aktív!

Ezt valoszinuleg nem kellene latni az archiv projekteknel (indulonal is lehetne mas szoveg). 

Egy masik kerdes, hogy egyebkent is talan mashogy kellene formazni ezt a mondatot, esetleg nem is mondatkent megjeleniteni.

A hiba [itt](https://github.com/legokor/legokor.hu/blob/79ad99f891c267b95c1ad68da66bfadf73de32f1/_layouts/project.html#L8) keresendo a kodban.

**Comment by Szibence** [comment]
A legokor.hu/projektek oldalon eddig is helyesnek látszott a projektek státusza, úgyhogy nem biztos, hogy szükség van a projektek leírásánál is kiírni ezt. Mindenesetre javítottam egyelőre a bugot, most már jól írja ki a státuszt.
